---
- name: Listen for newly created Namespace
  hosts: all
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 5050
        data_alerts_path:
        data_host_path: ImpactedEntityNames
        skip_original_data: true
  rules:
    - name: Set Resource Quotas to a Namespace
      condition: event.type == "ADDED"
      action:
        run_job_template:
          name: set-resource-quota-on-namespace
          organization: Default
