---
- name: Listen for newly created services in AAP
  hosts: all
  sources:
    - sabre1041.eda.k8s:
        api_version: v1
        kind: Service
  rules:
    - name: Patch a Route for activation-job
      condition:
        - event.type == "ADDED"
        - event.resource.metadata.namespace == "aap"
        - event.resource.metadata.name is regex("activation-job-[0-9]+-[0-9]+-5000")
      action:
        - debug:
        - print_event:
        - run_job_template:
          name: publis-eda-rb-route
          organization: Default
      job_args:
        extra_vars:
          activation_job_name: '{{ event.resource.metadata.name }}'
